### ISSUE TITLE
Edit Snapcraft.yaml to use GTK themes

### ISSUE THREAD

**Issue by nigelwarning** [sc0ty/subsync#104]
So,

All my snaps use the GTK theme, except for Subsync. So I did some research and I think because the yaml uses a different directory as most other Snaps.

Most snaps use 
```
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
```

While Subsync snap uses

```
 gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
```

Is it possible to change that? Or is there a way I can change that, so that the Subsync snap will use my system gtk theme.

Thanks!
